#!/bin/sh
set -e

mkdir -p "$HOME/.config/alacritty"
cp modules/alacritty/alacritty.toml "$HOME/.config/alacritty/alacritty.toml"

I3_CONFIG="$HOME/.config/i3/config"

if [ -f "$I3_CONFIG" ]; then
  sed -i 's/^bindsym $mod+Return/#bindsym $mod+Return/' "$I3_CONFIG"
  echo "\nbindsym \$mod+Return exec /usr/bin/alacritty" >> "$I3_CONFIG"
fi

SWAY_CONFIG="$HOME/.config/sway/config"

if [ -f "$SWAY_CONFIG" ]; then
  sed -i 's/^bindsym $mod+Return/#bindsym $mod+Return/' "$SWAY_CONFIG"
  echo "\nbindsym \$mod+Return exec /usr/bin/alacritty" >> "$SWAY_CONFIG"
fi
