#!/bin/bash
set -eo pipefail

. ./dist.conf

if [ -z "$1" ]; then
  echo "Please provide the module name!"
  exit 1
fi

if [ -f "modules/$1/${DISTRIBUTION}_repos" ]; then
  while read -r line; do
    IFS=';' read -ra ELEMS <<< "$line"
    echo "* Adding an external repo: ${ELEMS[1]}"

    # PPA (no key)
    if [ "$(echo "${ELEMS[0]}" | cut -c 1-4)" = "ppa:" ]; then
        add-apt-repository "${ELEMS[0]}"
    else
      keyname="/etc/apt/keyrings/$1.asc"

      curl -fsSL "${ELEMS[0]}" -o "$keyname"
      echo "deb [signed-by=$keyname] ${ELEMS[1]} ${ELEMS[3]} ${ELEMS[2]}" > "/etc/apt/sources.list.d/$1.list"
    fi
  done < <(cat "modules/$1/${DISTRIBUTION}_repos")

  apt update
fi

if [ -f "modules/$1/${DISTRIBUTION}_preinstall" ]; then
  sh "modules/$1/${DISTRIBUTION}_preinstall"
fi

if [ -f "modules/$1/${DISTRIBUTION}_packages" ]; then
  packages=$(cat "modules/$1/${DISTRIBUTION}_packages" | tr '\n' ' ')
  apt -y install $packages
fi

if command -v snap > /dev/null 2>&1; then
  if [ -f "modules/$1/snaps" ]; then
    while read -r line; do
      IFS=';' read -ra ELEMS <<< "$line"

      snap install ${ELEMS[0]} --"${ELEMS[1]}"
    done < <(cat "modules/$1/snaps")
  fi
fi
