#!/bin/bash
set -eo pipefail

. ./dist.conf

if [ -z "$1" ]; then
  echo "Please provide the module name!"
  exit 1
fi

if [ -f "modules/$1/${DISTRIBUTION}_repos" ]; then
  while read -r line; do
    IFS=';' read -ra ELEMS <<< "$line"
    echo "* Adding an external repo: ${ELEMS[1]}"

    # PPA (no key)
    if [ "$(echo "${ELEMS[0]}" | cut -c 1-4)" = "ppa:" ]; then
        add-apt-repository "${ELEMS[0]}"
    else
      curl -fsSL "${ELEMS[0]}" | apt-key add -
      if [ "${#ELEMS[@]}" -eq "3" ]; then
        add-apt-repository "${ELEMS[1]} $(lsb_release -cs) ${ELEMS[2]}"
      else
        add-apt-repository "${ELEMS[1]} ${ELEMS[3]} ${ELEMS[2]}"
      fi
    fi
  done < <(cat "modules/$1/${DISTRIBUTION}_repos")

  apt-get update
fi

if [ -f "modules/$1/${DISTRIBUTION}_packages" ]; then
  packages=$(cat "modules/$1/${DISTRIBUTION}_packages" | tr '\n' ' ')
  apt-get -y install $packages
fi

if [ -x "$(command -v snap)" ] && [ -f "modules/$1/snaps" ]; then
  while read -r line; do
    IFS=';' read -ra ELEMS <<< "$line"

    snap install ${ELEMS[0]} --"${ELEMS[1]}"
  done < <(cat "modules/$1/snaps")
fi
