#!/bin/sh

. ./dist.conf

if [ -z $1 ]; then
  echo "Please provide a $DISTRIBUTION package name!"
  exit 1
fi

find . -name "${DISTRIBUTION}_packages" \
  | xargs awk '{ print FILENAME "\t" $0 }' \
  | grep -P "\t.*$1.*$" \
  | awk -F '\t' '{ print $1 "/" $2 }' \
  | awk -F '/' '{ print $(NF-2) ": " $NF }' \
  | sort \
  | uniq \
  | cat

