#!/bin/sh

if [ "$(id -u)" -ne "0" ]; then
  echo "Run me as sudo."

  exit 1
fi

ufw allow ssh

cp modules/sshd/sshd_config /etc/ssh/sshd_config
cat modules/sshd/host.pub >> /etc/ssh/authorized_keys

# SSH
systemctl enable ssh
systemctl start ssh
