#!/bin/sh
set -e

# unmanaged executables
mkdir -p ~/bin

# nvim
mkdir -p ~/.config/nvim/bundle
mkdir -p ~/.config/nvim/vundle_plugins
mkdir -p ~/.config/nvim/swaps
mkdir -p ~/.config/nvim/backups

if ! [ -d ~/.config/nvim/bundle/Vundle.vim ]; then
  git clone https://github.com/VundleVim/Vundle.vim ~/.config/nvim/bundle/Vundle.vim
fi

if ! [ -f ~/.config/nvim/init.vim ]; then
  cp modules/essentials/init.vim ~/.config/nvim/init.vim
fi
nvim +PluginInstall +qall

# tmux
if ! [ -f ~/.tmux.conf ]; then
  cp modules/essentials/tmux.conf ~/.tmux.conf
fi

# git
if ! [ -f ~/.gitconfig ]; then
  cp modules/essentials/gitconfig ~/.gitconfig
fi

if ! [ -f ~/.gitignore ]; then
  cp modules/essentials/gitignore ~/.gitignore
fi

git config --global core.excludesfile ~/.gitignore

# zsh
ZSH_SCRIPTS=~/.zsh-scripts
mkdir -p ~/.oh-my-zsh-plugins
mkdir -p $ZSH_SCRIPTS

ZSH_SCRIPT_LOADING=$(cat <<SH
for script in $ZSH_SCRIPTS/*.zsh; do
  source \$script
done
SH
)

ZSH=~/.oh-my-zsh
if ! [ -d $ZSH ]; then
  # short version of the omz setup, but skips switching to zsh at the end
  # so that the other stuff can continue
  git clone --depth=1 https://github.com/robbyrussell/oh-my-zsh.git $ZSH

  if [ -f ~/.zshrc ] || [ -h ~/.zshrc ]; then
    mv ~/.zshrc ~/.zshrc.pre-oh-my-zsh;
  fi

  cp "$ZSH"/templates/zshrc.zsh-template ~/.zshrc
  sed -i "/^export ZSH=/ c\\
  export ZSH=\"$ZSH\"
  " ~/.zshrc

  sed -i 's/^plugins.*$/plugins=(`ls ~\/.oh-my-zsh-plugins`)/' ~/.zshrc

  echo "$ZSH_SCRIPT_LOADING" >> ~/.zshrc

  chsh -s "$(grep /zsh$ /etc/shells | tail -1)"
fi

# zsh syntax
git clone https://github.com/zdharma/fast-syntax-highlighting.git $ZSH/plugins/fast-syntax-highlighting

# ctags
if ! [ -f ~/.ctags ]; then
  cp modules/essentials/ctags ~/.ctags
fi

# ag
if ! [ -f ~/.ignore ]; then
  cp modules/essentials/ignore ~/.ignore
fi

# ag / git
if ! [ -f $ZSH_SCRIPTS/essentials.zsh ]; then
  cp modules/essentials/essentials.zsh $ZSH_SCRIPTS/essentials.zsh
fi

# ssh
mkdir -p ~/.ssh
if ! [ -f ~/.ssh/config ]; then
  cp modules/essentials/ssh-config ~/.ssh/config
fi
chmod 0700 ~/.ssh

# OpenAL
if ! [ -f ~/.alsoftrc ]; then
  cp modules/essentials/alsoftrc ~/.alsoftrc
fi
