#!/bin/sh

if [ "$(id -u)" -ne "0" ]; then
  echo "Run me as sudo."

  exit 1
fi

# UFW
ufw default deny
ufw allow ssh
ufw allow dns
ufw allow http
ufw enable

# SSH
systemctl enable ssh
systemctl start ssh

# sudo
echo "pi ALL=(ALL) PASSWD: ALL" > /etc/sudoers.d/010_pi-nopasswd

# DoH/cloudflared
wget https://bin.equinox.io/c/VdrWdbjqyF/cloudflared-stable-linux-arm.tgz
tar -xvzf ./cloudflared-stable-linux-arm.tgz
rm ./cloudflared-stable-linux.arm.tgz
mv ./cloudflared ~/bin/cloudflared

cp modules/pihole/cloudflared.opts /etc/default/cloudflared

chmod +x ~/bin/cloudflared
useradd -s /usr/sbin/nologin -r -M cloudflared
chown cloudflared:cloudflared /etc/default/cloudflared
chown cloudflared:cloudflared ~/bin/cloudflared

cp modules/pihole/cloudflared.service /etc/systemd/system/cloudflared.service
systemctl enable cloudflared
systemctl start cloudflared
