#!/bin/sh

if [ "$(id -u)" -ne "0" ]; then
  echo "Run me as sudo."

  exit 1
fi

# UFW
ufw default deny
ufw allow ssh
ufw allow dns
ufw allow http
ufw enable

# SSH
systemctl enable ssh
systemctl start ssh

# DoH/cloudflared
curl -o /usr/local/bin/cloudflared -L https://github.com/cloudflare/cloudflared/releases/2024.6.1/download/cloudflared-linux-arm64

cp modules/pihole/cloudflared.opts /etc/default/cloudflared

chmod +x /usr/local/bin/cloudflared
useradd -s /usr/sbin/nologin -r -M cloudflared
chown cloudflared:cloudflared /etc/default/cloudflared
chown cloudflared:cloudflared /usr/local/bin/cloudflared

cp modules/pihole/cloudflared.service /etc/systemd/system/cloudflared.service
systemctl enable cloudflared
systemctl start cloudflared

# dark power LED
(crontab -l 2>/dev/null; echo "@reboot bash -c \"echo 0 > /sys/devices/platform/leds/leds/PWR/brightness\"") | crontab -
