#!/bin/sh

if [ "$(id -u)" -ne "0" ]; then
  # PiHole
  curl -sSL https://install.pi-hole.net | bash
  echo "========================================="
  echo " sudo this script again"
  echo "========================================="

  exit 0
else
  if ! command -v pihole-FTL >/dev/null 2>&1; then
    echo "Use this script as sudo after installing PiHole non-sudo"
    exit 1
  fi
fi


# UFW
ufw allow dns
ufw allow http

DNSCRYPT_SOCKET=$(cat <<CFG
[Socket]
ListenStream=
ListenDatagram=
ListenStream=127.0.0.1:5054
ListenDatagram=127.0.0.1:5054
CFG
)

echo "$DNSCRYPT_SOCKET" >> /etc/systemd/system/dnscrypt-proxy.socket.d/override.conf

DNSYCRPT_CONFIG=$( <<CFG
listen_addresses = []
server_names = ['cloudflare']

[static.'cloudflare']
stamp = 'sdns://AgcAAAAAAAAADjEwNC4xNi4xMzIuMjI5ABJkbnMuY2xvdWRmbGFyZS5jb20KL2Rucy1xdWVyeQ'
CFG
)

echo "$DNSCRYPT_SOCKET" >> /etc/dnscrypt-proxy/dnscrypt-proxy.toml

systemctl daemon-reload
systemctl restart dnscrypt-proxy.socket
systemctl restart dnscrypt-proxy.service
systemctl restart pihole-FTL.service

pihole-FTL --config dns.upstreams '["127.0.0.1#5054"]'

# dark power LED
(crontab -l 2>/dev/null; echo "@reboot bash -c \"echo 0 > /sys/devices/platform/leds/leds/PWR/brightness\"") | crontab -
